# Generated by go2rpm 1.15.0
%bcond check 1

%global debug_package %{nil}

# https://github.com/int128/listener
%global goipath         github.com/int128/listener
Version:                1.3.0

%gometa -L -f

%global common_description %{expand:
Go package to allocate a net.Listener from address candidates or free port.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-int128-listener
Release:        %autorelease
Summary:        Go package to allocate a net.Listener from address candidates or free port

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
