# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/int128/oauth2dev
%global goipath         github.com/int128/oauth2dev
Version:                1.1.0
%global commit          55666ed298dd4fd0f5766e8b9ad7e8d802f6570b

%gometa -L -f

%global common_description %{expand:
Go package of OAuth 2.0 Device Authorization Grant (RFC 8628), compatible with
golang.org/x/oauth2.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-int128-oauth2dev
Release:        %autorelease
Summary:        Go package of OAuth 2.0 Device Authorization Grant (RFC 8628), compatible with golang.org/x/oauth2

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
