# Generated by go2rpm 1.15.0
%bcond check 1

%global debug_package %{nil}

# https://github.com/int128/oauth2cli
%global goipath         github.com/int128/oauth2cli
Version:                1.18.0

%gometa -L -f

%global common_description %{expand:
Go package of OAuth 2.0 authorization for command line tools, which allows
simple authorization flow for better UX.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-int128-oauth2cli
Release:        %autorelease
Summary:        Go package of OAuth 2.0 authorization for command line tools, which allows simple authorization flow for better UX

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
