# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/int128/oauth2cli
%global goipath         github.com/int128/oauth2cli
Version:                1.15.1

%gometa -L -f

%global common_description %{expand:
Go package of OAuth 2.0 authorization for command line tools, which allows
simple authorization flow for better UX.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           golang-github-int128-oauth2cli
Release:        %autorelease
Summary:        Go package of OAuth 2.0 authorization for command line tools, which allows simple authorization flow for better UX

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs README.md
%endif

%gopkgfiles

%changelog
%autochangelog
