# Generated by go2rpm 1.18.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/zalando/go-keyring
%global goipath         github.com/zalando/go-keyring
Version:                0.2.6
%global commit          5c6f7e0ba5bf0380b4a490f2b7e41deb44b3c63e

%gometa -L -f

%global common_description %{expand:
Cross-platform keyring interface for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md SECURITY.md

Name:           golang-github-zalando-keyring
Release:        %autorelease
Summary:        Cross-platform keyring interface for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
