# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/int128/listener
%global goipath         github.com/int128/listener
Version:                1.2.0

%gometa -L -f

%global common_description %{expand:
Go package to allocate a net.Listener from address candidates or free port.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-int128-listener
Release:        %autorelease
Summary:        Go package to allocate a net.Listener from address candidates or free port

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md
%endif

%gopkgfiles

%changelog
%autochangelog
